{{/*
Render CRD resources YAML (single or multi-document) with cert-manager annotation and
webhook namespace replaced by Release.Namespace (same pattern as kserve-llmisvc-resources).
Base file is generated by hack/setup/scripts/generate_chart_manifests.sh.

Parameters (dict):
  - baseFile: string - Path to the base file (e.g. "files/resources.yaml")
  - certName: string - The cert name after namespace (e.g. "llmisvc-serving-cert")
  - context: . - The root context for .Release, .Files, etc.
*/}}
{{- define "kserve-llmisvc-crd.renderCrdWithCertNamespace" -}}
{{- $baseContent := .context.Files.Get .baseFile -}}
{{- $baseContent = include "kserve-common.replaceNamespace" (list $baseContent .context.Release.Namespace) -}}
{{- $pattern := printf "cert-manager.io/inject-ca-from: kserve/%s" .certName -}}
{{- $replacement := printf "cert-manager.io/inject-ca-from: %s/%s" .context.Release.Namespace .certName -}}
{{- $baseContent = $baseContent | replace $pattern $replacement -}}
{{- $baseContent | nindent 0 -}}
{{- end -}}
